config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'rooms/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  Rails.application.routes.draw do
    get 'rooms/index'
    get '/signin', to: 'sessions#new'
    post '/signin', to: 'sessions#create'
    delete '/signout', to: 'sessions#destroy'
  end

  resources :rooms do
    resources :messages
  end
  resources :users
  resources :farms do
    resources :plots
  end

  root 'rooms#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/farm.rb
class Farm < ApplicationRecord
  belongs_to :room
  has_many :plots, dependent: :destroy
  after_commit { broadcast_update_to self.room }
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
  after_create_commit { broadcast_append_to self.room }

  def confirm_participant
    if self.room.is_private
      is_participant = Participant.where(user_id: self.user.id, room_id: self.room.id).first
      throw :abort unless is_participant
    end
  end
end

app/models/participant.rb
class Participant < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/plant.rb
# frozen_string_literal: true

# a single instance of a plant type, it will track it's growth stage and resources towards the next stage
class Plant < ApplicationRecord
  belongs_to :plant_type
  belongs_to :plot, touch: true

  def current_ascii_image
    plant_type.stages[growth_stage].ascii_image
  end

  def advance_stage
    if growth_stage < plant_type.stages.size - 1
      update(growth_stage: growth_stage + 1)
    else
      destroy
    end
  end
end

app/models/plant_type.rb
class PlantType < ApplicationRecord
  # this goes in fixtures later
  LETTUCE = {
    name: 'Lettuce',
    info: 'Any of several plants in the Asteracea family (just like sunflowers!) characterized by rapid growth of tasty leaves',
    stage_info: [
      {
        name: 'seed',
        ascii_image: '.',
        water_needs: 2,
        energy_needs: 2,
        absorbtion_rate: 1,
      },
      {
        name: 'seedling',
        ascii_image: 'v',
        water_needs: 5,
        energy_needs: 5,
        harvest_yield: 1,
        absorbtion_rate: 1,
      },
      {
        name: 'young',
        ascii_image: 't',
        water_needs: 10,
        energy_needs: 10,
        gather_yield: 1,
        harvest_yield: 2,
        absorbtion_rate: 2,
      },
      {
        name: 'mature',
        ascii_image: 'W',
        water_needs: 4,
        energy_needs: 4,
        gather_yield: 3,
        harvest_yield: 5,
        absorbtion_rate: 2,
      },
      {
        name: 'bolting',
        ascii_image: 'Y',
        water_needs: 5,
        energy_needs: 10,
        harvest_yield: 2,
        seeds: 4,
        absorbtion_rate: 3,
      },
      {
        name: 'dead',
        ascii_image: 'z',
        seeds: 20,
        absorbtion_rate: 0,
      }
    ]
  }

  def stages
    @_stages ||= stage_info.map {|data| PlantStage.new(**data)}
  end
end

class PlantStage
  include ActiveModel::API

  attr_accessor :name, :ascii_image, :image, :gather_yield, :harvest_yield, :seeds, :water_needs, :energy_needs, :absorbtion_rate

  def can_gather?
    !!gather_yield
  end

  def can_harvest?
    !!harvest_yield
  end
end

app/models/plot.rb
class Plot < ApplicationRecord
  belongs_to :farm, touch: true
  has_one :plant, dependent: :destroy
end

app/models/room.rb
class Room < ApplicationRecord
  validates_uniqueness_of :name
  scope :public_rooms, -> { where(is_private: false) }

  has_many :messages
  has_many :participants
  has_one :farm

  after_create_commit { broadcast_if_public }

  def broadcast_if_public
    broadcast_append_to "rooms" unless self.is_private
  end

  def self.create_private_room(users, room_name)
    single_room = Room.create(name: room_name, is_private: true)
    users.each do |user|
      Participant.create(user_id: user.id, room_id: single_room.id )
    end
    single_room
  end

  def build_initial_farm
    if !farm
      Farm.create(room: self, size: 1, plots: [Plot.new()])
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates_uniqueness_of :username
  scope :all_except, ->(user) { where.not(id: user) }
  after_create_commit { broadcast_append_to "users" }

  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
    if session[:user_id]
      @current_user  = User.find(session[:user_id])
    end
  end

  def log_in(user)
    session[:user_id] = user.id
    @current_user = user
    redirect_to root_path
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/controllers/farms_controller.rb
# frozen_string_literal: true

# the basic controller letting us create or change the farm objects
class FarmsController < ApplicationController
  def create
    @room = Room.find(params[:room_id])
    @room.build_initial_farm
    # respond to turbo stuff?
    redirect_to room_path(@room)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @current_user = current_user
    @message = @current_user.messages.create(content: msg_params[:content], room_id: params[:room_id])
  end

  private

  def msg_params
    params.require(:message).permit(:content)
  end
end

app/controllers/plots_controller.rb
# frozen_string_literal: true

# the basic controller letting us create or change the plot objects on the farm
class PlotsController < ApplicationController
  def create
    @farm = Farm.find(params[:id])
    @farm.plots.create
    # respond to turbo stuff?
    redirect_to room_path(@farm.room)
  end

  def update
    @farm = Farm.find(params[:farm_id])
    @plot = @farm.plots.find(params[:id])
    if @plot.plant
      @plot.plant.advance_stage
    else
      @plot.create_plant(plant_type: PlantType.first, growth_stage: 0)
    end
  end
end

app/controllers/rooms_controller.rb
# frozen_string_literal: true

# the basic controller letting us create, list, or show the chat rooms
class RoomsController < ApplicationController
  def index
    @current_user = current_user
    redirect_to '/signin' unless @current_user
    @rooms = Room.public_rooms
    @users = User.all_except(@current_user)
    @room = Room.new
  end

  def create
    @room = Room.create(name: params['room']['name'])
  end

  def show
    @current_user = current_user
    @single_room = Room.find(params[:id])
    @farm = @single_room&.farm || Farm.new
    @messages = @single_room.messages
    @rooms = Room.public_rooms
    @users = User.all_except(@current_user)
    @room = Room.new
    @message = Message.new

    render 'index'
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.find_by(username: params[:session][:username])
    if user
      log_in(user)
    else
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/farms/_farm.html.erb
<div class="farm" id="<%= dom_id farm %>">
  <%= render farm.plots.order(:created_at) %>
</div>

app/views/layouts/_dynamic_styles.html.erb
border-green-600
border-yellow-900

app/views/layouts/_new_message_form.html.erb
<div class="form-group msg-form">
  <%= form_with(model: [@single_room ,@message], remote: true, class: "d-flex",
        data: { controller: "reset-form", action: "turbo:submit-end->reset-form#reset" }) do |f| %>
    <%= f.text_field :content, id: 'chat-text', class: "form-control msg-content", autocomplete: 'off' %>
    <%= f.submit data: { disable_with: false }, class: "btn btn-primary" %>
  <% end %>
</div>

app/views/layouts/_new_room_form.html.erb
<%= form_with(model: @room, remote: true, class: "w-full",
      data: { controller: "reset-form", action: "turbo:submit-end->reset-form#reset" }) do |f| %>
  <%= f.text_field :name, class: "form-control w-full", autocomplete: 'off' %>
  <%= f.submit data: { disable_with: false } %>
<% end %>

app/views/layouts/_side_menu.html.erb
<div class="pb-4">
  <h5> Hi <%= @current_user.username %> </h5>
  <%= link_to 'Sign Out', signout_path, data: { "turbo-method": :delete } %>
</div>
<h4> Rooms </h4>
<%= render partial: "layouts/new_room_form" %>
<div>
  <%= turbo_stream_from "rooms" %>
  <div id="rooms">
    <%= render @rooms %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Farmchat</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <style>
      <%= ".msg-#{current_user&.id}" %> {
      background-color: #007bff !important;
      text-align: right
      }
      <%= ".cont-#{current_user&.id}" %> {
      display: flex;
      justify-content: flex-end
      }
    </style>
  </head>

  <body>
    <main class="container px-5 m-auto">
      <%= yield %>
    </main>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="cont-<%= message.user.id %>">
  <div class="msg-<%= message.user.id %> w-fit max-w-[60%] p-2 m-2 bg-gray-400 rounded-xl">
    <% unless message.room.is_private %>
      <h6 class="name"> <%= message.user.username %> </h6>
    <% end %>
  <%= message.content %>
  </div>
</div>

app/views/plants/_plant.html.erb
<div class="plant">
  <%= plant.current_ascii_image %>
</div>

app/views/plots/_plot.html.erb
<div class="inline plot border-4 m-3 border-solid  border-<%= plot.plant ? 'green-600' : 'yellow-900' %> rounded p-2" id="<%=dom_id plot%>">
  <%= link_to "[ #{plot.plant&.current_ascii_image || "&nbsp;"} ]".html_safe,
              farm_plot_path(plot.farm, plot),
              data: {'turbo-method': :patch} %>
</div>

app/views/rooms/_room.html.erb
<div> <%= link_to room.name, room %> </div>

app/views/rooms/index.html.erb
<div class="flex flex-row h-screen">
  <div class="basis-1/4 my-20 p-2 border-2 rounded border-gray-600 overflow-scroll">
    <div class="room-menu ">
      <%= render partial: "layouts/side_menu" %>
    </div>

  </div>
  <div class="basis-3/4 mt-20 mb-16 px-4">
    <% if @single_room %>
      <div class="farm-menu h-2/5">
        <h4 class="text-center"> <%= @single_room.name %> Farm </h4>
          <div id="<%= dom_id @single_room %>-farm">
            <% if @farm.id %>
              <%= render @farm %>
            <% else %>
              <p>There is no farm yet!</p>
              <%= link_to 'Build one', farms_path(room_id: @single_room.id), data: {'turbo-method': :post} %>
            <% end %>
          </div>
      </div>
      <div class="bg-gray-800 text-white chat-area h-2/5 overflow-scroll rounded">
        <h4 class="text-center"> <%= @single_room.name %> </h4>
        <%= turbo_stream_from @single_room %>
        <div id="messages">
          <%= render @messages %>
        </div>
      </div>
      <div class="py-2">
        <%= render partial: 'layouts/new_message_form' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/_user.html.erb
<div> <%= link_to user.username, user %> </div>